// services/tracks/mock-data.ts
import type { Track } from "./types";

export const MOCK_TRACKS: Track[] = [
  {
    id: "trk_001",
    title: "Neon Nights",
    description: "A hard-hitting trap beat with atmospheric synths and rolling 808s.",
    artistId: "art_001",
    artistName: "BeatsByKove",
    genre: "Trap",
    mood: ["Dark", "Energetic"],
    bpm: 140,
    key: "F#",
    duration: 187,
    coverImage: null,
    audioUrl: null,
    previewUrl: null,
    status: "published",
    isFeatured: true,
    createdAt: "2025-11-12T10:30:00Z",
    licenses: [
      { id: "lic_001a", trackId: "trk_001", name: "Basic", price: 29.99, streamLimit: 5000, distributionLimit: 2500, commercialUse: false },
      { id: "lic_001b", trackId: "trk_001", name: "Premium", price: 79.99, streamLimit: 100000, distributionLimit: 10000, commercialUse: true },
      { id: "lic_001c", trackId: "trk_001", name: "Unlimited", price: 149.99, streamLimit: null, distributionLimit: null, commercialUse: true },
    ],
    analytics: { salesCount: 312, revenue: 18420, plays: 54800, downloads: 892 },
  },
  {
    id: "trk_002",
    title: "Golden Hour",
    description: "Smooth R&B production with jazz-infused chords and a laid-back groove.",
    artistId: "art_002",
    artistName: "Lucid Waves",
    genre: "R&B",
    mood: ["Melodic", "Chill", "Romantic"],
    bpm: 87,
    key: "Bb",
    duration: 214,
    coverImage: null,
    audioUrl: null,
    previewUrl: null,
    status: "published",
    isFeatured: false,
    createdAt: "2025-10-28T14:15:00Z",
    licenses: [
      { id: "lic_002a", trackId: "trk_002", name: "Basic", price: 24.99, streamLimit: 5000, distributionLimit: 2500, commercialUse: false },
      { id: "lic_002b", trackId: "trk_002", name: "Premium", price: 59.99, streamLimit: 75000, distributionLimit: 8000, commercialUse: true },
    ],
    analytics: { salesCount: 188, revenue: 9320, plays: 31200, downloads: 544 },
  },
  {
    id: "trk_003",
    title: "Cold World",
    description: "UK drill instrumental with menacing strings and punchy percussion.",
    artistId: "art_003",
    artistName: "Phantom Beats",
    genre: "Drill",
    mood: ["Dark", "Aggressive"],
    bpm: 135,
    key: "C#",
    duration: 163,
    coverImage: null,
    audioUrl: null,
    previewUrl: null,
    status: "published",
    isFeatured: true,
    createdAt: "2025-12-01T08:00:00Z",
    licenses: [
      { id: "lic_003a", trackId: "trk_003", name: "Basic", price: 34.99, streamLimit: 5000, distributionLimit: 2500, commercialUse: false },
      { id: "lic_003b", trackId: "trk_003", name: "Premium", price: 89.99, streamLimit: 150000, distributionLimit: 15000, commercialUse: true },
      { id: "lic_003c", trackId: "trk_003", name: "Exclusive", price: 499.99, streamLimit: null, distributionLimit: null, commercialUse: true },
    ],
    analytics: { salesCount: 421, revenue: 31800, plays: 87300, downloads: 1240 },
  },
  {
    id: "trk_004",
    title: "Afro Vibes",
    description: "High-energy Afrobeats production with percussion layers and catchy melody.",
    artistId: "art_004",
    artistName: "SunKing",
    genre: "Afrobeats",
    mood: ["Energetic", "Uplifting"],
    bpm: 102,
    key: "G",
    duration: 198,
    coverImage: null,
    audioUrl: null,
    previewUrl: null,
    status: "draft",
    isFeatured: false,
    createdAt: "2026-01-05T11:45:00Z",
    licenses: [
      { id: "lic_004a", trackId: "trk_004", name: "Basic", price: 19.99, streamLimit: 3000, distributionLimit: 1000, commercialUse: false },
    ],
    analytics: { salesCount: 0, revenue: 0, plays: 1200, downloads: 23 },
  },
  {
    id: "trk_005",
    title: "Midnight Gospel",
    description: "Soulful gospel-influenced hip-hop with lush choir samples.",
    artistId: "art_001",
    artistName: "BeatsByKove",
    genre: "Gospel",
    mood: ["Uplifting", "Melodic"],
    bpm: 78,
    key: "A",
    duration: 232,
    coverImage: null,
    audioUrl: null,
    previewUrl: null,
    status: "published",
    isFeatured: false,
    createdAt: "2025-09-17T09:20:00Z",
    licenses: [
      { id: "lic_005a", trackId: "trk_005", name: "Basic", price: 29.99, streamLimit: 5000, distributionLimit: 2500, commercialUse: false },
      { id: "lic_005b", trackId: "trk_005", name: "Premium", price: 74.99, streamLimit: 100000, distributionLimit: 10000, commercialUse: true },
    ],
    analytics: { salesCount: 94, revenue: 5640, plays: 18900, downloads: 310 },
  },
  {
    id: "trk_006",
    title: "Warp Drive",
    description: "Future bass electronic track with evolving synths and complex drops.",
    artistId: "art_005",
    artistName: "Ether Sound",
    genre: "Electronic",
    mood: ["Energetic", "Cinematic"],
    bpm: 128,
    key: "D",
    duration: 275,
    coverImage: null,
    audioUrl: null,
    previewUrl: null,
    status: "archived",
    isFeatured: false,
    createdAt: "2025-07-22T16:00:00Z",
    licenses: [
      { id: "lic_006a", trackId: "trk_006", name: "Basic", price: 39.99, streamLimit: 5000, distributionLimit: 2500, commercialUse: false },
      { id: "lic_006b", trackId: "trk_006", name: "Premium", price: 99.99, streamLimit: null, distributionLimit: null, commercialUse: true },
    ],
    analytics: { salesCount: 57, revenue: 3420, plays: 9100, downloads: 180 },
  },
  {
    id: "trk_007",
    title: "Bounce Back",
    description: "Old-school Hip-Hop flavored with boom-bap drums and dusty samples.",
    artistId: "art_006",
    artistName: "Crate Digger",
    genre: "Hip-Hop",
    mood: ["Raw", "Energetic"],
    bpm: 92,
    key: "E",
    duration: 204,
    coverImage: null,
    audioUrl: null,
    previewUrl: null,
    status: "published",
    isFeatured: false,
    createdAt: "2025-11-30T13:10:00Z",
    licenses: [
      { id: "lic_007a", trackId: "trk_007", name: "Basic", price: 24.99, streamLimit: 5000, distributionLimit: 2500, commercialUse: false },
      { id: "lic_007b", trackId: "trk_007", name: "Premium", price: 64.99, streamLimit: 100000, distributionLimit: 10000, commercialUse: true },
      { id: "lic_007c", trackId: "trk_007", name: "Unlimited", price: 199.99, streamLimit: null, distributionLimit: null, commercialUse: true },
    ],
    analytics: { salesCount: 276, revenue: 15800, plays: 43600, downloads: 720 },
  },
  {
    id: "trk_008",
    title: "Blue Note",
    description: "Contemporary jazz fusion with mellow trumpet lines and brushed snares.",
    artistId: "art_007",
    artistName: "Miles & Co",
    genre: "Jazz",
    mood: ["Chill", "Melodic"],
    bpm: 112,
    key: "Ab",
    duration: 318,
    coverImage: null,
    audioUrl: null,
    previewUrl: null,
    status: "draft",
    isFeatured: false,
    createdAt: "2026-02-14T07:30:00Z",
    licenses: [],
    analytics: { salesCount: 0, revenue: 0, plays: 340, downloads: 0 },
  },
];
