// services/licensing/mock-data.ts
import type { LicensePlan } from "./types";

export const MOCK_LICENSE_PLANS: LicensePlan[] = [
  {
    id: "plan_001",
    name: "Basic",
    description: "Entry-level license for independent artists. Ideal for mixtapes, SoundCloud releases, and small projects.",
    defaultPrice: 29.99,
    isActive: true,
    commercialUse: false,
    streamingAllowed: true,
    radioAllowed: false,
    tvAllowed: false,
    monetizationAllowed: false,
    maxStreams: 5000,
    maxDistribution: 2500,
    territory: null,
    isExclusive: false,
    includesStems: false,
    includesWav: false,
    includesMp3: true,
    createdAt: "2025-08-01T10:00:00Z",
  },
  {
    id: "plan_002",
    name: "Premium",
    description: "Professional license for commercial releases, YouTube monetization, and music video production.",
    defaultPrice: 79.99,
    isActive: true,
    commercialUse: true,
    streamingAllowed: true,
    radioAllowed: true,
    tvAllowed: false,
    monetizationAllowed: true,
    maxStreams: 100000,
    maxDistribution: 10000,
    territory: null,
    isExclusive: false,
    includesStems: false,
    includesWav: true,
    includesMp3: true,
    createdAt: "2025-08-01T10:05:00Z",
  },
  {
    id: "plan_003",
    name: "Unlimited",
    description: "No-limit commercial license for major label releases, sync licensing, and full-scale distribution.",
    defaultPrice: 149.99,
    isActive: true,
    commercialUse: true,
    streamingAllowed: true,
    radioAllowed: true,
    tvAllowed: true,
    monetizationAllowed: true,
    maxStreams: null,
    maxDistribution: null,
    territory: null,
    isExclusive: false,
    includesStems: true,
    includesWav: true,
    includesMp3: true,
    createdAt: "2025-08-01T10:10:00Z",
  },
  {
    id: "plan_004",
    name: "Exclusive",
    description: "Full ownership transfer. Beat is removed from the store permanently after purchase.",
    defaultPrice: 499.99,
    isActive: true,
    commercialUse: true,
    streamingAllowed: true,
    radioAllowed: true,
    tvAllowed: true,
    monetizationAllowed: true,
    maxStreams: null,
    maxDistribution: null,
    territory: null,
    isExclusive: true,
    includesStems: true,
    includesWav: true,
    includesMp3: true,
    createdAt: "2025-08-01T10:15:00Z",
  },
];
