import type { Metadata } from "next";
import "./globals.css";
import { Plus_Jakarta_Sans } from "next/font/google";

const plusJakartaSans = Plus_Jakarta_Sans({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-plus-jakarta",
});

export const metadata: Metadata = {
  title: "SS dashboard",
  description: "Generated by create next app",
  icons: {
    icon: [
      {
        url: "/assets/logo/ss-no-bg.png",
        type: "image/png",
      },
    ],
    shortcut: ["/assets/logo/ss-no-bg.png"],
    apple: [
      {
        url: "/assets/logo/ss-no-bg.png",
        type: "image/png",
      },
    ],
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${plusJakartaSans.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
