// services/artists/mock-data.ts
import type { Artist } from "./types";

export const MOCK_ARTISTS: Artist[] = [
  {
    id: "a1",
    stageName: "KXNG Nova",
    realName: "Marcus Williams",
    biography: "Award-winning producer and beatmaker from Atlanta. Known for hard-hitting trap production and layered melodic elements. Credits include platinum records and Grammy-nominated projects.",
    profileImage: "https://picsum.photos/seed/kxng/300/300",
    bannerImage: "https://picsum.photos/seed/kxngbanner/1200/400",
    country: "United States",
    primaryGenre: "Hip-Hop",
    genres: ["Hip-Hop", "Trap", "R&B"],
    artistType: "producer",
    isVerified: true,
    isFeatured: true,
    status: "active",
    email: "marcus@kxngnova.com",
    phone: "+1 404 555 0182",
    website: "https://kxngnova.com",
    managementCompany: "Nova Management Group",
    bookingEmail: "booking@kxngnova.com",
    socials: [
      { platform: "instagram", url: "https://instagram.com/kxngnova" },
      { platform: "spotify", url: "https://open.spotify.com/artist/kxngnova" },
      { platform: "youtube", url: "https://youtube.com/@kxngnova" },
      { platform: "tiktok", url: "https://tiktok.com/@kxngnova" },
    ],
    totalTracks: 48,
    totalCollections: 6,
    totalSales: 1240,
    totalRevenue: 37200,
    totalDownloads: 9800,
    totalStreams: 284000,
    createdAt: "2024-08-15T10:00:00Z",
    updatedAt: "2025-06-01T08:00:00Z",
    tracks: [
      { id: "t1", title: "Solar Drift", genre: "Trap", coverImage: null, licenseCount: 3, sales: 412, revenue: 8240, status: "published" },
      { id: "t2", title: "Static Rain", genre: "Hip-Hop", coverImage: null, licenseCount: 2, sales: 274, revenue: 5480, status: "published" },
      { id: "t3", title: "Glass Horizon", genre: "R&B", coverImage: null, licenseCount: 3, sales: 198, revenue: 3960, status: "published" },
    ],
    collections: [
      { id: "c1", name: "Nova Essentials Vol. 1", coverImage: null, trackCount: 12, revenue: 14800 },
      { id: "c2", name: "Trap Gods Bundle", coverImage: null, trackCount: 8, revenue: 9600 },
    ],
  },
  {
    id: "a2",
    stageName: "Aura Keys",
    realName: "Aaliyah Thompson",
    biography: "Multi-genre artist and keyboardist blending neo-soul, R&B, and electronic music. Based in London with a global reach across streaming platforms.",
    profileImage: "https://picsum.photos/seed/aura/300/300",
    bannerImage: null,
    country: "United Kingdom",
    primaryGenre: "R&B",
    genres: ["R&B", "Neo Soul", "Electronic"],
    artistType: "singer",
    isVerified: true,
    isFeatured: false,
    status: "active",
    email: "aura@aurakeys.co.uk",
    phone: null,
    website: "https://aurakeys.co.uk",
    managementCompany: null,
    bookingEmail: null,
    socials: [
      { platform: "instagram", url: "https://instagram.com/aurakeys" },
      { platform: "apple_music", url: "https://music.apple.com/artist/aura-keys" },
      { platform: "soundcloud", url: "https://soundcloud.com/aurakeys" },
    ],
    totalTracks: 31,
    totalCollections: 3,
    totalSales: 788,
    totalRevenue: 23640,
    totalDownloads: 5400,
    totalStreams: 187000,
    createdAt: "2024-09-10T10:00:00Z",
    updatedAt: "2025-05-20T12:00:00Z",
    tracks: [
      { id: "t4", title: "Midnight Bloom", genre: "R&B", coverImage: null, licenseCount: 3, sales: 389, revenue: 7780, status: "published" },
      { id: "t5", title: "Velvet Keys", genre: "Neo Soul", coverImage: null, licenseCount: 2, sales: 211, revenue: 4220, status: "published" },
    ],
    collections: [
      { id: "c3", name: "Soulful Sessions", coverImage: null, trackCount: 10, revenue: 8200 },
    ],
  },
  {
    id: "a3",
    stageName: "Phasma",
    realName: null,
    biography: "Electronic producer and sound designer known for cinematic ambient textures and experimental beat compositions. Works under full anonymity.",
    profileImage: "https://picsum.photos/seed/phasma/300/300",
    bannerImage: null,
    country: "Germany",
    primaryGenre: "Electronic",
    genres: ["Electronic", "Ambient", "Experimental"],
    artistType: "producer",
    isVerified: false,
    isFeatured: false,
    status: "active",
    email: "contact@phasmasound.de",
    phone: null,
    website: null,
    managementCompany: null,
    bookingEmail: null,
    socials: [
      { platform: "soundcloud", url: "https://soundcloud.com/phasma" },
      { platform: "youtube", url: "https://youtube.com/@phasmasound" },
    ],
    totalTracks: 22,
    totalCollections: 2,
    totalSales: 341,
    totalRevenue: 10230,
    totalDownloads: 2800,
    totalStreams: 94000,
    createdAt: "2024-11-01T10:00:00Z",
    updatedAt: "2025-04-15T09:00:00Z",
    tracks: [
      { id: "t6", title: "Chrome Waves", genre: "Electronic", coverImage: null, licenseCount: 2, sales: 198, revenue: 3960, status: "published" },
    ],
    collections: [],
  },
  {
    id: "a4",
    stageName: "Luma Sol",
    realName: "Sofia Reyes",
    biography: "Afrobeats and Latin fusion producer based in Miami. Creates high-energy, dance-floor-ready productions blending global rhythms with modern trap sensibilities.",
    profileImage: "https://picsum.photos/seed/luma/300/300",
    bannerImage: "https://picsum.photos/seed/lumabanner/1200/400",
    country: "United States",
    primaryGenre: "Afrobeats",
    genres: ["Afrobeats", "Latin", "Trap"],
    artistType: "producer",
    isVerified: true,
    isFeatured: true,
    status: "active",
    email: "sofia@lumasol.com",
    phone: "+1 305 555 0291",
    website: "https://lumasol.com",
    managementCompany: "Sol Agency",
    bookingEmail: "bookings@lumasol.com",
    socials: [
      { platform: "instagram", url: "https://instagram.com/lumasol" },
      { platform: "tiktok", url: "https://tiktok.com/@lumasol" },
      { platform: "spotify", url: "https://open.spotify.com/artist/lumasol" },
      { platform: "facebook", url: "https://facebook.com/lumasolmusic" },
    ],
    totalTracks: 19,
    totalCollections: 4,
    totalSales: 621,
    totalRevenue: 18630,
    totalDownloads: 4100,
    totalStreams: 143000,
    createdAt: "2025-01-05T10:00:00Z",
    updatedAt: "2025-06-10T14:00:00Z",
    tracks: [
      { id: "t7", title: "Neon Veil", genre: "Afrobeats", coverImage: null, licenseCount: 3, sales: 299, revenue: 5980, status: "published" },
      { id: "t8", title: "Fuego Nights", genre: "Latin", coverImage: null, licenseCount: 2, sales: 180, revenue: 3600, status: "draft" },
    ],
    collections: [
      { id: "c4", name: "Afro Fusion Pack", coverImage: null, trackCount: 6, revenue: 7200 },
    ],
  },
  {
    id: "a5",
    stageName: "Drift Echo",
    realName: "James Park",
    biography: "Lo-fi and chill-hop producer from Seoul. Crafts nostalgic, late-night soundscapes rooted in jazz and hip-hop tradition.",
    profileImage: null,
    bannerImage: null,
    country: "South Korea",
    primaryGenre: "Lo-Fi",
    genres: ["Lo-Fi", "Chillhop", "Jazz Hop"],
    artistType: "producer",
    isVerified: false,
    isFeatured: false,
    status: "active",
    email: "james@driftecho.kr",
    phone: null,
    website: null,
    managementCompany: null,
    bookingEmail: null,
    socials: [
      { platform: "youtube", url: "https://youtube.com/@driftecho" },
      { platform: "soundcloud", url: "https://soundcloud.com/driftecho" },
    ],
    totalTracks: 14,
    totalCollections: 1,
    totalSales: 203,
    totalRevenue: 6090,
    totalDownloads: 1900,
    totalStreams: 78000,
    createdAt: "2025-02-20T10:00:00Z",
    updatedAt: "2025-05-30T10:00:00Z",
    tracks: [],
    collections: [],
  },
  {
    id: "a6",
    stageName: "SolarFX",
    realName: "David Osei",
    biography: "Afrobeats and Drill fusion producer from Accra. Brings a fresh West African perspective to contemporary trap production.",
    profileImage: "https://picsum.photos/seed/solarfx/300/300",
    bannerImage: null,
    country: "Ghana",
    primaryGenre: "Afrobeats",
    genres: ["Afrobeats", "Drill", "Afro Drill"],
    artistType: "producer",
    isVerified: false,
    isFeatured: false,
    status: "archived",
    email: "david@solarfx.gh",
    phone: null,
    website: null,
    managementCompany: null,
    bookingEmail: null,
    socials: [
      { platform: "instagram", url: "https://instagram.com/solarfx" },
    ],
    totalTracks: 9,
    totalCollections: 0,
    totalSales: 88,
    totalRevenue: 2640,
    totalDownloads: 620,
    totalStreams: 31000,
    createdAt: "2024-12-10T10:00:00Z",
    updatedAt: "2025-03-01T10:00:00Z",
    tracks: [],
    collections: [],
  },
];

export const COUNTRIES = [
  "United States", "United Kingdom", "Germany", "France", "Canada",
  "Australia", "Nigeria", "Ghana", "South Africa", "Brazil",
  "Japan", "South Korea", "Jamaica", "Colombia", "Mexico",
];

export const GENRES = [
  "Hip-Hop", "Trap", "R&B", "Afrobeats", "Drill", "Electronic",
  "Pop", "Lo-Fi", "Gospel", "Jazz", "Reggae", "Latin", "Soul", "Ambient",
];

export const ARTIST_TYPES = [
  { value: "producer", label: "Producer" },
  { value: "singer", label: "Singer / Vocalist" },
  { value: "band", label: "Band / Group" },
  { value: "dj", label: "DJ" },
  { value: "composer", label: "Composer" },
  { value: "songwriter", label: "Songwriter" },
  { value: "engineer", label: "Audio Engineer" },
  { value: "other", label: "Other" },
];
