// services/media/mock-data.ts
import type { MediaAsset, MediaActivity, MediaReference, MediaVersion } from "./types";

function daysAgo(n: number) {
  const d = new Date(); d.setDate(d.getDate() - n); return d.toISOString();
}
function fmtBytes(mb: number) { return Math.round(mb * 1024 * 1024); }
function fakeChecksum() {
  return Array.from({ length: 16 }, () => Math.floor(Math.random() * 16).toString(16)).join("");
}

const ADMINS = ["John Carter", "Sarah Support"];

function makeActivity(assetId: string, actions: Array<{ action: MediaActivity["action"]; by: string; notes: string; daysBack: number }>): MediaActivity[] {
  return actions.map((a, i) => ({
    id: `act-${assetId}-${i}`,
    assetId,
    action: a.action,
    performedBy: a.by,
    notes: a.notes,
    createdAt: daysAgo(a.daysBack),
  }));
}

function makeVersions(assetId: string, count: number): MediaVersion[] {
  return Array.from({ length: count }, (_, i) => ({
    id: `ver-${assetId}-${i}`,
    assetId,
    version: count - i,
    storageKey: `assets/${assetId}/v${count - i}`,
    size: fmtBytes(0.8 + i * 0.2),
    changeNotes: i === 0 ? "Current version" : i === 1 ? "Minor color correction" : "Original upload",
    uploadedBy: ADMINS[i % 2],
    uploadedAt: daysAgo(i * 10),
  }));
}

const MOCK_REFS: Record<string, MediaReference[]> = {
  "ast-001": [
    { id: "ref-1", assetId: "ast-001", entityType: "track", entityId: "trk-001", entityTitle: "Midnight Bloom", fieldName: "coverImage", url: "/music/tracks" },
    { id: "ref-2", assetId: "ast-001", entityType: "homepage", entityId: "hs-2", entityTitle: "Featured Tracks Section", fieldName: "background", url: "/content" },
    { id: "ref-3", assetId: "ast-001", entityType: "blog", entityId: "post-002", entityTitle: "Top 10 Trap Producers", fieldName: "featuredImage", url: "/content" },
  ],
  "ast-002": [
    { id: "ref-4", assetId: "ast-002", entityType: "artist", entityId: "art-001", entityTitle: "KXNG Nova", fieldName: "profileImage", url: "/music/artists" },
    { id: "ref-5", assetId: "ast-002", entityType: "collection", entityId: "col-001", entityTitle: "Nova Essentials Vol. 1", fieldName: "artistThumb", url: "/music/collections" },
  ],
  "ast-003": [
    { id: "ref-6", assetId: "ast-003", entityType: "homepage", entityId: "hs-1", entityTitle: "Hero Banner", fieldName: "backgroundImage", url: "/content" },
  ],
  "ast-004": [],
  "ast-005": [
    { id: "ref-7", assetId: "ast-005", entityType: "track", entityId: "trk-002", entityTitle: "Solar Drift", fieldName: "previewAudio", url: "/music/tracks" },
  ],
  "ast-006": [
    { id: "ref-8", assetId: "ast-006", entityType: "product", entityId: "prod-001", entityTitle: "KXNG Trap Essentials", fieldName: "downloadFile", url: "/products/sound-kits" },
  ],
  "ast-007": [
    { id: "ref-9", assetId: "ast-007", entityType: "blog", entityId: "post-001", entityTitle: "How to License Music", fieldName: "featuredImage", url: "/content" },
    { id: "ref-10", assetId: "ast-007", entityType: "marketing", entityId: "mkt-1", entityTitle: "Email Campaign Q4", fieldName: "headerImage", url: "/marketing" },
  ],
  "ast-008": [],
};

export const MOCK_ASSETS: MediaAsset[] = [
  {
    id: "ast-001",
    filename: "midnight-bloom-cover.webp",
    originalFilename: "Midnight Bloom Cover Art.png",
    mimeType: "image/webp",
    extension: "webp",
    assetType: "image",
    size: fmtBytes(0.34),
    width: 1200, height: 1200,
    duration: null,
    checksum: fakeChecksum(),
    url: "https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=400&q=80",
    thumbnailUrl: "https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=200&q=60",
    status: "active",
    uploadedBy: "John Carter",
    usageCount: 3,
    metadata: { altText: "Midnight Bloom track cover art", caption: "Cover for Midnight Bloom by Aura Keys", description: "", tags: ["cover", "track", "r&b"], copyright: "© 2025 Sidez", creator: "Studio AI", dominantColor: "#6b21a8", colorPalette: ["#6b21a8", "#1e1b4b", "#f3e8ff"] },
    versions: makeVersions("ast-001", 2),
    references: MOCK_REFS["ast-001"],
    activity: makeActivity("ast-001", [
      { action: "uploaded", by: "John Carter", notes: "Initial upload", daysBack: 30 },
      { action: "metadata_updated", by: "Sarah Support", notes: "Added alt text and tags", daysBack: 25 },
      { action: "replaced", by: "John Carter", notes: "Higher resolution version", daysBack: 10 },
    ]),
    createdAt: daysAgo(30), updatedAt: daysAgo(10),
  },
  {
    id: "ast-002",
    filename: "kxng-nova-profile.jpg",
    originalFilename: "KXNG Nova Profile Photo.jpg",
    mimeType: "image/jpeg",
    extension: "jpg",
    assetType: "image",
    size: fmtBytes(0.82),
    width: 800, height: 800,
    duration: null,
    checksum: fakeChecksum(),
    url: "https://images.unsplash.com/photo-1598488035139-bdbb2231ce04?w=400&q=80",
    thumbnailUrl: "https://images.unsplash.com/photo-1598488035139-bdbb2231ce04?w=200&q=60",
    status: "active",
    uploadedBy: "Sarah Support",
    usageCount: 2,
    metadata: { altText: "KXNG Nova artist photo", caption: "Official profile photo", description: "High-res artist photo for KXNG Nova", tags: ["artist", "profile", "hip-hop"], copyright: "© KXNG Nova 2025", creator: "Photo Studio NYC", dominantColor: "#111827", colorPalette: ["#111827", "#374151", "#9ca3af"] },
    versions: makeVersions("ast-002", 1),
    references: MOCK_REFS["ast-002"],
    activity: makeActivity("ast-002", [
      { action: "uploaded", by: "Sarah Support", notes: "Artist onboarding", daysBack: 45 },
      { action: "downloaded", by: "John Carter", notes: "", daysBack: 20 },
    ]),
    createdAt: daysAgo(45), updatedAt: daysAgo(45),
  },
  {
    id: "ast-003",
    filename: "homepage-hero-banner.webp",
    originalFilename: "Hero Banner Summer 2025.png",
    mimeType: "image/webp",
    extension: "webp",
    assetType: "image",
    size: fmtBytes(1.4),
    width: 1920, height: 1080,
    duration: null,
    checksum: fakeChecksum(),
    url: "https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=400&q=80",
    thumbnailUrl: "https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=200&q=60",
    status: "active",
    uploadedBy: "John Carter",
    usageCount: 1,
    metadata: { altText: "Homepage hero banner", caption: "Summer 2025 homepage banner", description: "Main hero image for website homepage", tags: ["homepage", "banner", "marketing"], copyright: "© 2025 Sidez", creator: "Design Team", dominantColor: "#0f172a", colorPalette: ["#0f172a", "#7c3aed", "#06b6d4"] },
    versions: makeVersions("ast-003", 3),
    references: MOCK_REFS["ast-003"],
    activity: makeActivity("ast-003", [
      { action: "uploaded", by: "John Carter", notes: "Summer campaign", daysBack: 20 },
      { action: "replaced", by: "Sarah Support", notes: "Updated text overlay", daysBack: 12 },
      { action: "replaced", by: "John Carter", notes: "Final approved version", daysBack: 5 },
    ]),
    createdAt: daysAgo(20), updatedAt: daysAgo(5),
  },
  {
    id: "ast-004",
    filename: "sidez-logo-white.svg",
    originalFilename: "Sidez Logo White.svg",
    mimeType: "image/svg+xml",
    extension: "svg",
    assetType: "image",
    size: fmtBytes(0.02),
    width: 200, height: 60,
    duration: null,
    checksum: fakeChecksum(),
    url: "/assets/logo/ss-no-bg.png",
    thumbnailUrl: "/assets/logo/ss-no-bg.png",
    status: "active",
    uploadedBy: "John Carter",
    usageCount: 0,
    metadata: { altText: "Sidez logo", caption: "White version for dark backgrounds", description: "", tags: ["logo", "brand"], copyright: "© 2025 Sidez", creator: "Design Team", dominantColor: "#ffffff", colorPalette: ["#ffffff"] },
    versions: makeVersions("ast-004", 1),
    references: MOCK_REFS["ast-004"],
    activity: makeActivity("ast-004", [
      { action: "uploaded", by: "John Carter", notes: "Brand assets", daysBack: 90 },
    ]),
    createdAt: daysAgo(90), updatedAt: daysAgo(90),
  },
  {
    id: "ast-005",
    filename: "solar-drift-preview.mp3",
    originalFilename: "Solar Drift Preview Clip.mp3",
    mimeType: "audio/mpeg",
    extension: "mp3",
    assetType: "audio",
    size: fmtBytes(2.1),
    width: null, height: null,
    duration: 30,
    checksum: fakeChecksum(),
    url: "",
    thumbnailUrl: null,
    status: "active",
    uploadedBy: "John Carter",
    usageCount: 1,
    metadata: { altText: "", caption: "30-second preview clip", description: "Preview clip for Solar Drift by KXNG Nova", tags: ["preview", "audio", "trap"], copyright: "© KXNG Nova 2025", creator: "KXNG Nova", dominantColor: null, colorPalette: [] },
    versions: makeVersions("ast-005", 2),
    references: MOCK_REFS["ast-005"],
    activity: makeActivity("ast-005", [
      { action: "uploaded", by: "John Carter", notes: "Track preview upload", daysBack: 15 },
      { action: "replaced", by: "John Carter", notes: "Re-encoded at 192kbps", daysBack: 8 },
    ]),
    createdAt: daysAgo(15), updatedAt: daysAgo(8),
  },
  {
    id: "ast-006",
    filename: "kxng-trap-essentials-v1.2.zip",
    originalFilename: "KXNG Trap Essentials Main Download v1.2.zip",
    mimeType: "application/zip",
    extension: "zip",
    assetType: "zip",
    size: fmtBytes(248),
    width: null, height: null,
    duration: null,
    checksum: fakeChecksum(),
    url: "",
    thumbnailUrl: null,
    status: "active",
    uploadedBy: "John Carter",
    usageCount: 1,
    metadata: { altText: "", caption: "Main download ZIP for KXNG Trap Essentials", description: "Contains 500+ drum samples, loops, and MIDI files", tags: ["download", "sound-kit", "zip", "trap"], copyright: "© 2025 Sidez", creator: "KXNG Nova", dominantColor: null, colorPalette: [] },
    versions: makeVersions("ast-006", 2),
    references: MOCK_REFS["ast-006"],
    activity: makeActivity("ast-006", [
      { action: "uploaded", by: "John Carter", notes: "Product v1.0 upload", daysBack: 60 },
      { action: "replaced", by: "Sarah Support", notes: "v1.2 — 20 new samples", daysBack: 14 },
      { action: "downloaded", by: "System", notes: "Customer download", daysBack: 3 },
    ]),
    createdAt: daysAgo(60), updatedAt: daysAgo(14),
  },
  {
    id: "ast-007",
    filename: "blog-licensing-guide-hero.jpg",
    originalFilename: "Licensing Guide Blog Hero.jpg",
    mimeType: "image/jpeg",
    extension: "jpg",
    assetType: "image",
    size: fmtBytes(0.55),
    width: 1200, height: 630,
    duration: null,
    checksum: fakeChecksum(),
    url: "https://images.unsplash.com/photo-1511379938547-c1f69419868d?w=400&q=80",
    thumbnailUrl: "https://images.unsplash.com/photo-1511379938547-c1f69419868d?w=200&q=60",
    status: "active",
    uploadedBy: "Sarah Support",
    usageCount: 2,
    metadata: { altText: "Music licensing guide illustration", caption: "Header image for licensing guide post", description: "OG image for blog and social sharing", tags: ["blog", "og-image", "licensing"], copyright: "© Unsplash / Pixabay", creator: "Unsplash", dominantColor: "#b45309", colorPalette: ["#b45309", "#78350f", "#fef3c7"] },
    versions: makeVersions("ast-007", 1),
    references: MOCK_REFS["ast-007"],
    activity: makeActivity("ast-007", [
      { action: "uploaded", by: "Sarah Support", notes: "Blog content upload", daysBack: 25 },
      { action: "metadata_updated", by: "John Carter", notes: "Added copyright info", daysBack: 20 },
    ]),
    createdAt: daysAgo(25), updatedAt: daysAgo(20),
  },
  {
    id: "ast-008",
    filename: "sidez-terms-of-service-2025.pdf",
    originalFilename: "Terms of Service 2025.pdf",
    mimeType: "application/pdf",
    extension: "pdf",
    assetType: "document",
    size: fmtBytes(0.18),
    width: null, height: null,
    duration: null,
    checksum: fakeChecksum(),
    url: "",
    thumbnailUrl: null,
    status: "active",
    uploadedBy: "John Carter",
    usageCount: 0,
    metadata: { altText: "", caption: "Terms of Service document", description: "Legal ToS for platform users", tags: ["legal", "document", "tos"], copyright: "© 2025 Sidez", creator: "Legal Team", dominantColor: null, colorPalette: [] },
    versions: makeVersions("ast-008", 1),
    references: MOCK_REFS["ast-008"],
    activity: makeActivity("ast-008", [
      { action: "uploaded", by: "John Carter", notes: "Legal document upload", daysBack: 10 },
    ]),
    createdAt: daysAgo(10), updatedAt: daysAgo(10),
  },
];
